export const componentTagMap: { [key: string]: string } = {
    'table': 'ui-table',
    'chart': 'ui-chart',
    'spacer': 'ui-spacer',
    'grid': 'ui-grid',
    'timeline': 'ui-timeline',
    'stream': 'ui-stream',
    'carousel': 'ui-carousel',
    'card': 'ui-card',
    'text': 'ui-text',
    'code-block': 'ui-code-block',
    'image': 'ui-image',
    'video': 'ui-video',
    'icon': 'ui-icon',
    'button': 'ui-button',
    'link': 'ui-link',
    'badge': 'ui-badge',
    'progress': 'ui-progress',
    'loading': 'ui-loading',
    'box': 'ui-box',
    'divider': 'ui-divider',
    'tabs': 'ui-tabs',
    'collapse-block': 'ui-collapse-block',
    'reference': 'ui-reference',
};
